_Tests_GMapBundle_ServiceExists:
    pattern: /_tests/GMapBundle/ServiceExists
    defaults: { _controller: GMapBundle:Tests:serviceExists }
    
_Tests_GMapBundle_ServiceClass:
    pattern: /_tests/GMapBundle/ServiceClass
    defaults: { _controller: GMapBundle:Tests:serviceClass }
    
_Tests_GMapBundle_GeocoderAddress1:
    pattern: /_tests/GMapBundle/GeocoderAddress1/{address}
    defaults: { _controller: GMapBundle:Tests:geocoderAddress1 }
    
_Tests_GMapBundle_GeocoderAddress2:
    pattern: /_tests/GMapBundle/GeocoderAddress2/{address}
    defaults: { _controller: GMapBundle:Tests:geocoderAddress2 }
    
_Tests_GMapBundle_GeocoderLatLng1:
    pattern: /_tests/GMapBundle/GeocoderLatLng1/{lat}/{lng}
    defaults: { _controller: GMapBundle:Tests:geocoderLatLng1 }
    
_Tests_GMapBundle_GeocoderLatLng2:
    pattern: /_tests/GMapBundle/GeocoderLatLng2/{lat}/{lng}
    defaults: { _controller: GMapBundle:Tests:geocoderLatLng2 }
    
_Tests_GMapBundle_GeocoderLatLng3:
    pattern: /_tests/GMapBundle/GeocoderLatLng3/{latLng}
    defaults: { _controller: GMapBundle:Tests:geocoderLatLng3 }
    
_Tests_GMapBundle_GeocoderComponents1:
    pattern: /_tests/GMapBundle/GeocoderComponents1/{address}
    defaults: { _controller: GMapBundle:Tests:geocoderComponents1 }
    
_Tests_GMapBundle_GeocoderComponents2:
    pattern: /_tests/GMapBundle/GeocoderComponents2/{address}
    defaults: { _controller: GMapBundle:Tests:geocoderComponents2 }
    
_Tests_GMapBundle_GeocoderComponents3:
    pattern: /_tests/GMapBundle/GeocoderComponents3/{address}
    defaults: { _controller: GMapBundle:Tests:geocoderComponents3 }
    
_Tests_GMapBundle_PolylineEncoder:
    pattern: /_tests/GMapBundle/PolylineEncoder
    defaults: { _controller: GMapBundle:Tests:polylineEncoder }
    
_Tests_GMapBundle_ElevationIteration:
    pattern: /_tests/GMapBundle/ElevationIteration
    defaults: { _controller: GMapBundle:Tests:elevationIteration }